---
name: cd
on: workflow_dispatch

env:
  AWS_REGION: "ap-northeast-1"
  IAM_ROLE_ARN: ${{ secrets.IAM_ROLE_ARN }}
  AWS_BUCKET_NAME: "websiteBucket"
  CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: v20
          cache: yarn
          cache-dependency-path: ./app/yarn.lock
        
      - name: Build
        run: yarn install & yarn build:prod

      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.IAM_ROLE_ARN }}

      - name: Setup aws cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64

      - name: Upload files to S3 bucket and Clear CF cache
        run: |
          aws s3 sync --exact-timestamps --delete ./dist s3://${{ env.AWS_BUCKET_NAME }}/
          aws cloudfront create-invalidation --distribution-id ${{ env.CF_DISTRIBUTION_ID }} --paths "/*"